name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/github-action-package
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>üè∑Ô∏è</text></svg>

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: ./build/CONTRIBUTORS.svg

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.7
        with:
          package-path: ./package.json
      
      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@v1.5.7

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: package.json info
        id: info
        uses: ./

      - run: echo "name - ${{ steps.info.outputs.name }}"
      - run: echo "version - ${{ steps.info.outputs.version }}"
      - run: echo "description - ${{ steps.info.outputs.description }}"
      - run: echo "author - ${{ steps.info.outputs.author }}"
      - run: echo "homepage - ${{ steps.info.outputs.homepage }}"
      - run: echo "license - ${{ steps.info.outputs.license }}"
      - run: echo "keywords - ${{ steps.info.outputs.keywords }}"
      - run: echo "repository - ${{ steps.info.outputs.repository }}"
      - run: echo "os - ${{ steps.info.outputs.os }}"
      - run: echo "cpu - ${{ steps.info.outputs.cpu }}"

      - name: package.json info
        id: info2
        uses: ./
        with:
          data: |
            {
              "name": "@jaywcjlove/github-action-package-test"
            }

      - run: echo "name - ${{ steps.info2.outputs.name }}"
      - run: echo "version - ${{ steps.info2.outputs.version }}"
      - run: echo "description - ${{ steps.info2.outputs.description }}"
      - run: echo "author - ${{ steps.info2.outputs.author }}"
      - run: echo "homepage - ${{ steps.info2.outputs.homepage }}"
      - run: echo "license - ${{ steps.info2.outputs.license }}"
      - run: echo "keywords - ${{ steps.info2.outputs.keywords }}"
      - run: echo "repository - ${{ steps.info2.outputs.repository }}"
      - run: echo "os - ${{ steps.info2.outputs.os }}"
      - run: echo "cpu - ${{ steps.info2.outputs.cpu }}"

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.5.7
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (renovate-bot|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-package/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }}  

            ```yaml
            - name: package.json info
              id: info
              uses: jaywcjlove/github-action-package@main

            - run: echo "name - ${{ steps.info.outputs.name }}"
            - run: echo "version - ${{ steps.info.outputs.version }}"
            - run: echo "description - ${{ steps.info.outputs.description }}"
            - run: echo "author - ${{ steps.info.outputs.author }}"
            ```

            ```yaml
            - name: package.json info
              id: info
              uses: jaywcjlove/github-action-package@main
              with:
                data: |
                  {
                    "name": "@jaywcjlove/github-action-package-test"
                  }

            - run: echo "name - ${{ steps.info.outputs.name }}"
            - run: echo "version - ${{ steps.info.outputs.version }}"
            - run: echo "description - ${{ steps.info.outputs.description }}"
            - run: echo "author - ${{ steps.info.outputs.author }}"
            ```

            ${{ steps.changelog.outputs.changelog }}